# Generated by Django 6.0.2 on 2026-02-21 05:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_phone_number_alter_user_role_authlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authlog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('register', 'Register'), ('refresh', 'Refresh'), ('password_change', 'Change Password')], max_length=20, verbose_name='Action'),
        ),
        migrations.AlterField(
            model_name='authlog',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='authlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_logs', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='authlog',
            name='user_agent',
            field=models.TextField(blank=True, verbose_name='User Agent'),
        ),
    ]
