# Generated by Django 6.0.2 on 2026-02-24 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_refreshtoken'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RefreshToken',
            new_name='RefreshTokenModel',
        ),
        migrations.AddIndex(
            model_name='authlog',
            index=models.Index(fields=['user', 'created_at'], name='users_authl_user_id_f7b41f_idx'),
        ),
    ]
