# Generated by Django 6.0.2 on 2026-03-10 06:03

import apps.users.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_is_active_alter_user_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.users.managers.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='verifyotp',
            name='user',
        ),
        migrations.AddField(
            model_name='verifyotp',
            name='phone_number',
            field=models.CharField(default=0, max_length=13, verbose_name='Phone Number'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='verifyotp',
            name='code',
            field=models.CharField(max_length=4),
        ),
    ]
