# Generated by Django 6.0.2 on 2026-03-11 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_managers_remove_verifyotp_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=100, verbose_name='E-Mail')),
                ('verify_type', models.CharField(choices=[('phone_number', 'Phone number'), ('email', 'Email')], default='email')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameModel(
            old_name='VerifyOTP',
            new_name='PhoneVerify',
        ),
    ]
