# Generated by Django 6.0.2 on 2026-03-16 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_emailverify_verify_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverify',
            name='user_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
